### ISSUE TITLE
ReuireContext and RequireActivity description isn't accurate

### ISSUE THREAD

**Issue by humblerookie** [wajahatkarim3/Today-I-Learned#1]
Topic
  https://github.com/wajahatkarim3/Today-I-Learned/blob/master/android/req-act.md

Section
`Now, this method will make sure that Fragment is attached and returns a valid non-null Activity which we can use without any trouble.`

This part isn't true in fact I'm not really sure of the purpose of these methods since they throw an `IllegalStateException` if your activity is detached rather than the nullable context unwrapping method.

Ref:
```@NonNull
    public final Context requireContext() {
        Context context = getContext();
        if (context == null) {
            throw new IllegalStateException("Fragment " + this + " not attached to a context.");
        }
        return context;
    }

**Comment by wajahatkarim3** [comment]
Yeah. I updated the article but on Medium and forgot to update it here. Thanks for pointing this. I have updated it here as well 😄
